### ISSUE TITLE
Wistia Responsive

### ISSUE THREAD

**Issue by JanaOBX** [anderly/wistia-responsive#2]
We are moving away from Youtube, and hope to rely on Wistia as a video platform, however, the videos have to be responsive. The Wistia Responsive Wordpress plugin does not seem to be working with our site. Any advice?

**Comment by anderly** [comment]
Please try updating to the latest version (1.1.1). This corrects an issue with protocol relative URLs and should work on your site.

**Comment by JanaOBX** [comment]
Decided to use the foam structured link, which resolved the problem.  We were using the latest version of the plugin, so there must have been a theme conflict.  Thanks!
